// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import * as dotenv from 'dotenv';
import path from 'path/win32';

dotenv.config({ path: path.resolve(__dirname, '.env') });

console.log(
  'Checking DB URL:',
  process.env.DATABASE_URL ? 'FOUND' : 'NOT FOUND',
);

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
